### ISSUE TITLE
getLuckyUserHistoryId()返回值多了个问号👀

### ISSUE THREAD

**Issue by esssios** [gebilaofan/juejinCheckIn#2]
![image](https://user-images.githubusercontent.com/65351073/151107547-e92707a6-f017-4ae7-b2b3-880539264310.png)

**Comment by wakaka378** [comment]
这不是多了个？  是js的可选链  相当于一个判断  可以看一下语法使用  [可选链操作符](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by esssios** [comment]
> 这不是多了个？ 是js的可选链 相当于一个判断 可以看一下语法使用 [可选链操作符](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
Soga，学到了学到了，多谢大佬指点
